//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai1_Buoi08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public string madonhang { get; set; }
        public string masach { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> dongia { get; set; }
    
        public virtual dondathang dondathang { get; set; }
        public virtual sach sach { get; set; }
    }
}
