//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai1_Buoi08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dondathang
    {
        public dondathang()
        {
            this.chitietdonhangs = new HashSet<chitietdonhang>();
        }
    
        public string madonhang { get; set; }
        public string datthanhtoan { get; set; }
        public string tinhtrangdonhang { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public Nullable<System.DateTime> ngaygiao { get; set; }
        public string makh { get; set; }
    
        public virtual ICollection<chitietdonhang> chitietdonhangs { get; set; }
        public virtual khachhang khachhang { get; set; }
    }
}
