//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai1_Buoi08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public khachhang()
        {
            this.dondathangs = new HashSet<dondathang>();
        }
    
        public string makh { get; set; }
        public string hoten { get; set; }
        public string taikhoan { get; set; }
        public string matkhau { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
    
        public virtual ICollection<dondathang> dondathangs { get; set; }
    }
}
