//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai1_Buoi08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhaxuatban
    {
        public nhaxuatban()
        {
            this.saches = new HashSet<sach>();
        }
    
        public string manxb { get; set; }
        public string tennxh { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
    
        public virtual ICollection<sach> saches { get; set; }
    }
}
