//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai1_Buoi08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sach
    {
        public sach()
        {
            this.chitietdonhangs = new HashSet<chitietdonhang>();
            this.vietsaches = new HashSet<vietsach>();
        }
    
        public string masach { get; set; }
        public string tensach { get; set; }
        public Nullable<decimal> giaban { get; set; }
        public string mota { get; set; }
        public string anhbia { get; set; }
       
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<int> soluongton { get; set; }
        public string macd { get; set; }
        public string manxb { get; set; }
    
        public virtual ICollection<chitietdonhang> chitietdonhangs { get; set; }
        public virtual chude chude { get; set; }
        public virtual nhaxuatban nhaxuatban { get; set; }
        public virtual ICollection<vietsach> vietsaches { get; set; }
    }
}
