//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai1_Buoi08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tacgia
    {
        public tacgia()
        {
            this.vietsaches = new HashSet<vietsach>();
        }
    
        public string matg { get; set; }
        public string tentg { get; set; }
        public string diachi { get; set; }
        public string tieusu { get; set; }
        public string dienthoai { get; set; }
    
        public virtual ICollection<vietsach> vietsaches { get; set; }
    }
}
