CREATE DATABASE QL_TINTUC
USE QL_TINTUC
CREATE TABLE THELOAITIN (
	IDLOAI INT NOT NULL PRIMARY KEY,
	TENTHELOAI NVARCHAR(100)
)
CREATE TABLE TINTUC (
	IDTIN INT NOT NULL PRIMARY KEY,
	IDLOAI INT ,
	TIEUDETIN NVARCHAR(100),
	NOIDUNGTIN NTEXT ,
	CONSTRAINT FK_TINTUC_THELOAITIN FOREIGN KEY(IDLOAI) REFERENCES THELOAITIN(IDLOAI)
)
select * from THELOAITIN
select * from TINTUC