//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THELOAITIN
    {
        public THELOAITIN()
        {
            this.TINTUCs = new HashSet<TINTUC>();
        }
    
        public int IDLOAI { get; set; }
        public string TENTHELOAI { get; set; }
    
        public virtual ICollection<TINTUC> TINTUCs { get; set; }
    }
}
