//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int IDTIN { get; set; }
        public Nullable<int> IDLOAI { get; set; }
        public string TIEUDETIN { get; set; }
        public string NOIDUNGTIN { get; set; }
    
        public virtual THELOAITIN THELOAITIN { get; set; }
    }
}
